
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 22 16:30:33 PET 2024
//----------------------------------------------------

package analizadorsintactcarrito;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int APAGAR_MOTOR = 17;
  public static final int NUMERO = 35;
  public static final int ENCENDER_MOTOR = 16;
  public static final int ACTIVAR_BOCINA = 13;
  public static final int AJUSTAR_VELOCIDAD = 18;
  public static final int N_DECIMAL = 38;
  public static final int SET_ESPACIO = 6;
  public static final int FIN_RECORRIDO = 19;
  public static final int USAR_SENSOR_DISTANCIA = 22;
  public static final int D_PUNTOS = 49;
  public static final int PLACA = 34;
  public static final int PARENTESIS_ABIERTO = 44;
  public static final int ORIENTACION = 20;
  public static final int CARRO = 2;
  public static final int AVANZAR = 8;
  public static final int IDENTIFICADOR = 37;
  public static final int AJUSTAR_ORIENTACION = 21;
  public static final int CAMBIAR_NOMBRE = 26;
  public static final int CAMBIAR_COLOR = 15;
  public static final int ESPACIO = 5;
  public static final int GUION = 47;
  public static final int D_PG2 = 43;
  public static final int D_PG1 = 41;
  public static final int MAIN = 4;
  public static final int POSICION_INICIAL = 7;
  public static final int EOF = 0;
  public static final int CARGAR_BATERIA = 25;
  public static final int error = 1;
  public static final int COMILLA = 32;
  public static final int COMA = 48;
  public static final int DIAGNOSTICAR = 23;
  public static final int MARCA = 40;
  public static final int USAR_SENSOR_PROXIMIDAD = 14;
  public static final int ERROR = 50;
  public static final int NAME = 36;
  public static final int TRAZAR_RUTA = 28;
  public static final int COLOR = 33;
  public static final int MAYOR = 42;
  public static final int RETROCEDER = 11;
  public static final int SI_PROXIMIDAD = 31;
  public static final int DETENER = 10;
  public static final int NIVEL_BATERIA = 24;
  public static final int P_COMA = 46;
  public static final int PARENTESIS_CERRADO = 45;
  public static final int ESPERAR = 30;
  public static final int AJUSTAR_SONIDO = 27;
  public static final int DEF = 3;
  public static final int NUMERO_G = 39;
  public static final int PATRON_MOVIMIENTO = 29;
  public static final int GIRAR = 9;
  public static final int ENCENDER_LUCES = 12;
}

