

package analizadorsintactcarrito;


public enum TokensCarrito {
    // Comandos principales del carrito
    CARRO, ESPACIO, SET_ESPACIO, POSICION_INICIAL, AVANZAR, GIRAR, DETENER, RETROCEDER, 
    ENCENDER_LUCES, ACTIVAR_BOCINA, USAR_SENSOR_PROXIMIDAD, CAMBIAR_COLOR, 
    ENCENDER_MOTOR, APAGAR_MOTOR, AJUSTAR_VELOCIDAD, FIN_RECORRIDO, 

    // Comandos adicionales del carrito
    DEF, MAIN, ORIENTACION, AJUSTAR_ORIENTACION, USAR_SENSOR_DISTANCIA, 
    DIAGNOSTICAR, NIVEL_BATERIA, CARGAR_BATERIA, CAMBIAR_NOMBRE, AJUSTAR_SONIDO, 
    TRAZAR_RUTA, PATRON_MOVIMIENTO, ESPERAR, SI_PROXIMIDAD,

    // Elementos de expresión
    NUMERO, N_DECIMAL, NUMERO_G, COLOR, MARCA, TAMAÑO, PLACA, NAME, IDENTIFICADOR,

    // Símbolos y operadores
    COMA, PARENTESIS_ABIERTO, PARENTESIS_CERRADO, COMILLA, GUION, 
    P_COMA, D_PUNTOS, D_PG1, D_PG2, MAYOR,

    // Errores
    ERROR
}

